1. Create a pandas DataFrame from the following dictionary and assign it to a variable named students_df. Print the dataframe.

In [2]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan'],
        'Age': [22, 23, 24, 22, 25],
        'Major': ['Biology', 'Computer Science', 'Mathematics', 'Physics', 'Chemistry']}

students_df = pd.DataFrame(data)
print(students_df)

      Name  Age             Major
0    Alice   22           Biology
1      Bob   23  Computer Science
2  Charlie   24       Mathematics
3    Diana   22           Physics
4     Evan   25         Chemistry

2. Display the first 3 rows of students_df.

In [3]:
students_df.head(3)

      Name  Age             Major
0    Alice   22           Biology
1      Bob   23  Computer Science
2  Charlie   24       Mathematics

3. Select and print the Age and Major columns from students_df.

In [4]:
students_df[["Age", "Major"]]

   Age             Major
0   22           Biology
1   23  Computer Science
2   24       Mathematics
3   22           Physics
4   25         Chemistry

4. Add a new column to students_df named GradYear with values [2022, 2023, 2023, None, 2024]. Print the updated DataFrame.

In [5]:
students_df["GradYear"] = [2022, 2023, 2023, None, 2024]
print(students_df)

      Name  Age             Major  GradYear
0    Alice   22           Biology    2022.0
1      Bob   23  Computer Science    2023.0
2  Charlie   24       Mathematics    2023.0
3    Diana   22           Physics       NaN
4     Evan   25         Chemistry    2024.0

5. Filter students_df to a new DataFrame filtered_df to keep only students majoring in Computer Science or Physics. Print the filtered DataFrame.

In [7]:
filtered_df = students_df[(students_df['Major']=='Computer Science')|(students_df['Major'] == 'Physics')]

print(filtered_df)

    Name  Age             Major  GradYear
1    Bob   23  Computer Science    2023.0
3  Diana   22           Physics       NaN

6. Select and print the second and fourth rows of students_df using their integer location.

In [8]:
print(students_df.iloc[[1,3]])

    Name  Age             Major  GradYear
1    Bob   23  Computer Science    2023.0
3  Diana   22           Physics       NaN

7. Delete the Age column from students_df and print the resulting DataFrame.

In [9]:
students_df.drop('Age', axis=1, inplace=True)
print(students_df)

      Name             Major  GradYear
0    Alice           Biology    2022.0
1      Bob  Computer Science    2023.0
2  Charlie       Mathematics    2023.0
3    Diana           Physics       NaN
4     Evan         Chemistry    2024.0

8. Fill all the missing values in GradYear with 2023 and print the DataFrame. Also, make sure the datatype for GradYear is int.

In [10]:
students_df.fillna({"GradYear" : 2023}, inplace=True)
students_df["GradYear"] = students_df["GradYear"].astype(int)
print(students_df)

      Name             Major  GradYear
0    Alice           Biology      2022
1      Bob  Computer Science      2023
2  Charlie       Mathematics      2023
3    Diana           Physics      2023
4     Evan         Chemistry      2024

9. Group students_df by Major and calculate the average GradYear for each major. Print the results.

In [11]:
students_df.groupby("Major")["GradYear"].mean()

Major
Biology             2022.0
Chemistry           2024.0
Computer Science    2023.0
Mathematics         2023.0
Physics             2023.0
Name: GradYear, dtype: float64

10. Create a new DataFrame sorted_df storing the sorted version of students_df by the GradYear in descending order. Print the first 3 records.

In [12]:
sorted_df = students_df.sort_values(by="GradYear", ascending=False)
sorted_df.head(3)

      Name             Major  GradYear
4     Evan         Chemistry      2024
1      Bob  Computer Science      2023
2  Charlie       Mathematics      2023

11. Filter students_df to find students who are majoring in Chemistry or whose GradYear is before 2023. Store them in a new DataFrame advanced_filter_df. Print the filtered DataFrame.

In [13]:
advanced_filter_df = students_df[(students_df["Major"]=="Chemistry") | (students_df["GradYear"]<2023)]
advanced_filter_df

    Name      Major  GradYear
0  Alice    Biology      2022
4   Evan  Chemistry      2024

12. Iterate over students_df rows and print the name of each student along with their major if their GradYear is 2023.

In [14]:
for index, row in students_df.iterrows():
    if row["GradYear"]==2023:
        print(f"Name :{row['Name']}, Major: {row['Major']}")

Name :Bob, Major: Computer Science
Name :Charlie, Major: Mathematics
Name :Diana, Major: Physics